#!/bin/sh

# Get relative path of the root directory of the project
rdir=`git rev-parse --git-dir`
rel_path="$(dirname "$rdir")"

# Change to that path and run the file
cd $rel_path

echo "pre-push hook started..."

source .env/bin/activate || source .env/Scripts/activate
pytest || exit 1

exit 0
